### PR TITLE
0.11.0-nightly changes and Bug Fixes

### PR DESCRIPTION
**Pull request by alexlianides**
- Update all devcontainer.jsons to refernce 0.11.0-nightly artifacts
- fix pathing for sampleData file for dotnet-starter-app
- fixed namespace usings for platform-mts-plugin-starter
- fixed debugPayloadApp for vth-plugin-starter

### CODE REVIEW

**Comment by alexlianides** [comment]
ship detector:
image

**Comment by alexlianides** [comment]
host-base-platform:
image

**Comment by alexlianides** [comment]
dotnet-starter-app:
image

**Comment by alexlianides** [comment]
platform-mts-ccp-sample-plugin:
image

**Comment by alexlianides** [comment]
hostsvc-link-plugin-starter:
image

**Comment by alexlianides** [comment]
hostsvc-logging-starter-plugin:
image

**Comment by alexlianides** [comment]
hostsvc-position-plugin-starter:
image

**Comment by alexlianides** [comment]
hostsvc-sensor-plugin-starter:
image

**Comment by alexlianides** [comment]
hostsvc-sensor-plugin-starter:
image

**Comment by alexlianides** [comment]
platform-mts-plugin-starter:
image

**Comment by alexlianides** [comment]
vth-plugin-starter:
image

**Review by daweins — APPROVED** [review]

**Pull request merged**
